name: microservices
extensions:
- name: seq
  logPath: ./.logs
services:
- name: backend
  project: backend/backend.csproj
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development  
  - name: UseFeatureManagement
    value: True
  - name: FeatureManagement__StaticWeatherAPI
    value: True
  - name: FeatureManagement__ExternalWeatherAPI
    value: False
  - name: AzureMapSubscriptionKey
    value: <Azure-Map-Subscription-Key>
  - name: UseExporter
    value: "zipkin"
  - name: Zipkin__ServiceName
    value: "backend"  
- name: frontend
  project: frontend/frontend.csproj
  env: 
  - name: ASPNETCORE_ENVIRONMENT
    value: Development  
  - name: UseExporter
    value: "zipkin"
  - name: Zipkin__ServiceName
    value: "frontend"
- name: webstatus
  project: webstatus/webstatus.csproj
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
- name: zipkin
  image: openzipkin/zipkin
  bindings:
  - port: 9411
- name: redis
  image: redis
  bindings:
  - port: 6379
    connectionString: "${host}:${port}"